require:
  - rubocop-performance
  - rubocop-require_tools
  - rubocop-rspec
  - rubocop-thread_safety
AllCops:
  NewCops: enable
  ParserEngine: parser_prism
  TargetRubyVersion: 3.3
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
RSpec/DescribedClass:
  SafeAutoCorrect: true
Naming/FileName:
  Exclude:
    - Gemfile
